---
- name: "Add NOPASSWD rule for the current user"
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_user_id }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: ansible_user_id != 'root'
  with_items:
    - "{{ ansible_user_id }}\tALL=(ALL) NOPASSWD:ALL"

- name: "Copy bashrc"
  copy:
    src: "{{ role_path }}/files/bash/bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
- name: "Copy tmux.conf"
  copy:
    src: "{{ role_path }}/files/tmux/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: "Copy Neovim"
  copy:
    src: "{{ role_path }}/files/nvim"
    dest: "{{ ansible_env.HOME }}/.config/"
- name: "Copy ranger Config"
  copy:
    src: "{{ role_path }}/files/ranger"
    dest: "{{ ansible_env.HOME }}/.config/"

- name: "Install base packages ... env ..."
  pacman:
    name:
      - neovim
      - ranger
      - tmux
      - rust
      - go
      - code
    state: latest
  become: true
  become_method: sudo

- name: "Install packages for fonts"
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - ttf-font-awesome
      - ttf-roboto-mono
      - adobe-source-sans-fonts
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-tw-fonts
      - adobe-source-han-sans-hk-fonts
      - adobe-source-han-sans-otc-fonts
      - adobe-source-serif-fonts
      - adobe-source-han-serif-cn-fonts
      - adobe-source-han-serif-tw-fonts
      - adobe-source-han-serif-hk-fonts
      - adobe-source-han-serif-otc-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - wqy-bitmapfont
      - wqy-microhei
      - wqy-microhei-lite
      - wqy-zenhei
    state: latest
  become: true
  become_method: sudo

  - name: "Link VSCode-oss Profile to VSCode"
  shell: |
    ln -s ~/.vscode-oss ~/.vscode