---
- name: "Sarch"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo Debug"
      debug: 
        msg: "{{ ansible_env.HOME }}"
  roles:
    - role: "roles/configure-base-env"
    - role: "roles/configure-desktop"
    - role: "roles/install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: {{ ansible_user_id }}
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
            - DEVSENSE.phptools-vscode
            - rust-lang.rust-analyzer
            - golang.Go
            - dracula-theme.theme-dracula
