---
- name: "Sarch"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo Debug"
      debug: 
        msg: "{{ ansible_env.HOME }}"
  roles:
    - role: "roles/configure-base-env"
    - role: "roles/configure-desktop"
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - snyk-security.snyk-vulnerability-scanner
            - DEVSENSE.phptools-vscode
            - rust-lang.rust-analyzer
            - golang.Go
            - dracula-theme.theme-dracula
            - MS-CEINTL.vscode-language-pack-zh-hans
          visual_studio_code_settings_overwrite: true
          visual_studio_code_settings: {
            "workbench.colorTheme": "Dracula",
            "editor.fontSize": 24,
          }
    - role: "roles/install-tools"